In [2]:
import math
import statistics

import numpy as np
import pandas as pd
from scipy.io import loadmat

In [3]:

data1 = loadmat(
    r"D:\Sem-5\PR\Project-1\sEMG_Basic_Hand_movements_upatras\Database 1\female_1.mat")

data2 = loadmat(
    r"D:\Sem-5\PR\Project-1\sEMG_Basic_Hand_movements_upatras\Database 1\female_2.mat")

data3 = loadmat(
    r"D:\Sem-5\PR\Project-1\sEMG_Basic_Hand_movements_upatras\Database 1\female_3.mat")

data4 = loadmat(
    r"D:\Sem-5\PR\Project-1\sEMG_Basic_Hand_movements_upatras\Database 1\male_1.mat")

data5 = loadmat(
    r"D:\Sem-5\PR\Project-1\sEMG_Basic_Hand_movements_upatras\Database 1\male_2.mat")

# data6 = loadmat(
#     r"D:\Sem-5\PR\Project-1\sEMG_Basic_Hand_movements_upatras\Database 2\male_day_1")

# data7 = loadmat(
#     r"D:\Sem-5\PR\Project-1\sEMG_Basic_Hand_movements_upatras\Database 2\male_day_2")

# data8 = loadmat(
#     r"D:\Sem-5\PR\Project-1\sEMG_Basic_Hand_movements_upatras\Database 2\male_day_3")

data = []
data.append(data1)
data.append(data2)
data.append(data3)
data.append(data4)
data.append(data5)
# data.append(data6)
# data.append(data7)
# data.append(data8)

keys = ['cyl_ch1', 'cyl_ch2', 'hook_ch1', 'hook_ch2', 'tip_ch1', 'tip_ch2',
        'palm_ch1', 'palm_ch2', 'spher_ch1', 'spher_ch2', 'lat_ch1', 'lat_ch2']


class CreateData:
    def __init__(self, data, keys) -> None:
        self.data = data
        self.keys = keys

    def combine(self):
        Gload_DataSet = pd.DataFrame()
        for i in self.data:
            MeanDataSet = pd.DataFrame()
            for j in keys:
                MeanDataSet = self.Mean_Data(
                    pd.DataFrame(i[j]), j, MeanDataSet)
            MeanDataSet = self.label(MeanDataSet)
            SkewDataset = pd.DataFrame()
            for j in keys:
                SkewDataset = self.Skew_Data(
                    pd.DataFrame(i[j]), j, SkewDataset)
            SkewDataset = self.label(SkewDataset)
            VarianceDataset = pd.DataFrame()
            for j in keys:
                VarianceDataset = self.Varince_Data(
                    pd.DataFrame(i[j]), j, VarianceDataset)
            VarianceDataset = self.label(VarianceDataset)
            KurtosisDataset = pd.DataFrame()
            for j in keys:
                KurtosisDataset = self.Varince_Data(
                    pd.DataFrame(i[j]), j, KurtosisDataset)
            KurtosisDataset = self.label(KurtosisDataset)

            Combined_Data = pd.DataFrame()
            Combined_Data = self.CombineDataSets(Combined_Data, MeanDataSet)
            Combined_Data = self.CombineDataSets(Combined_Data, SkewDataset)
            Combined_Data = self.CombineDataSets(
                Combined_Data, VarianceDataset)
            Combined_Data = self.CombineDataSets(Combined_Data, MeanDataSet)
            Gload_DataSet = self.CombineDataSets(Gload_DataSet,Combined_Data)
        return Gload_DataSet

    def Mean_Data(self, olddata, attr, DataSet):
        for i in range(0, 3000, 300):
            new_name = attr + 'feature_'+str(int(i/300))
            if (i == 0):
                DataSet[new_name] = (olddata.iloc[:, i:i+299].mean(axis=1))
            else:
                DataSet[new_name] = (olddata.iloc[:, i-50:i+299].mean(axis=1))
        return DataSet

    def Skew_Data(self, olddata, attr, DataSet):
        for i in range(0, 3000, 300):
            new_name = attr + 'feature_'+str(int(i/300))
            if (i == 0):
                DataSet[new_name] = (olddata.iloc[:, i:i+299].skew(axis=1))
            else:
                DataSet[new_name] = (olddata.iloc[:, i-50:i+299].skew(axis=1))
        return DataSet

    def Varince_Data(self, olddata, attr, DataSet):
        for i in range(0, 3000, 300):
            new_name = attr + 'feature_'+str(int(i/300))
            if (i == 0):
                df = pd.DataFrame(olddata.iloc[:, i:i+299])
                DataSet[new_name] = df.var(axis='columns')
            else:
                df = pd.DataFrame(olddata.iloc[:, i:i+299])
                DataSet[new_name] = df.var(axis='columns')
        return DataSet

    def Kurtosis_Data(self, olddata, attr, DataSet):
        for i in range(0, 3000, 300):
            new_name = attr + 'feature_'+str(int(i/300))
            if (i == 0):
                df = pd.DataFrame(olddata.iloc[:, i:i+299])
                DataSet[new_name] = df.kurt(axis=1)
            else:
                df = pd.DataFrame(olddata.iloc[:, i:i+299])
                DataSet[new_name] = df.kurt(axis=1)
        return DataSet

    def label(self, newdata):
        newdata2 = newdata.transpose()
        newdata2['target'] = ""
        for j in range(0, 10):
            newdata2.iat[12*j, -1] = 1
            newdata2.iat[12*j+1, -1] = 1
            newdata2.iat[12*j+2, -1] = 2
            newdata2.iat[12*j+3, -1] = 2
            newdata2.iat[12*j+4, -1] = 3
            newdata2.iat[12*j+5, -1] = 3
            newdata2.iat[12*j+6, -1] = 4
            newdata2.iat[12*j+7, -1] = 4
            newdata2.iat[12*j+8, -1] = 5
            newdata2.iat[12*j+9, -1] = 5
            newdata2.iat[12*j+10, -1] = 6
            newdata2.iat[12*j+11, -1] = 6
        return newdata2

    def CombineDataSets(self,Newdata, newdata):
        return pd.concat([newdata, Newdata], axis=0, ignore_index=True)


x = CreateData(data=data, keys=keys)
data = x.combine()
data.shape


C:\Users\Ruchita Gayatri\AppData\Local\Temp\ipykernel_25164\1267292100.py:81: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  DataSet[new_name] = (olddata.iloc[:, i:i+299].mean(axis=1))
C:\Users\Ruchita Gayatri\AppData\Local\Temp\ipykernel_25164\1267292100.py:83: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  DataSet[new_name] = (olddata.iloc[:, i-50:i+299].mean(axis=1))
C:\Users\Ruchita Gayatri\AppData\Local\Temp\ipykernel_25164\1267292100.py:90: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of 

(2400, 31)

In [4]:
X = data.iloc[:, :-1]
Y = data.iloc[:, -1]
Y=Y.astype('int')

Train Test Split 

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.25, random_state=0)

Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


Logistic Regression Classifier

In [7]:
from sklearn.linear_model import LogisticRegression
regression = LogisticRegression(random_state=0)
regression.fit(X_train, y_train)
score_Logistic = (regression.score(X_train, y_train))*4


In [8]:
from sklearn.metrics import r2_score
reg_pred = regression.predict(X_test)
r2_score = r2_score(y_test, reg_pred)
print('R2 Score: ', "%.2f" % (-(r2_score)))

R2 Score:  0.90


SVM Classifier

In [9]:
from sklearn.svm import SVC
rbf = SVC(kernel='rbf',gamma=0.5,C=0.1).fit(X_train,y_train) # RBF Kernel
poly = SVC(kernel='poly',degree=3,C=1).fit(X_train,y_train) # Polynomial Kernel 
 

In [10]:
poly_pred = poly.predict(X_test)
rbf_pred = rbf.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

poly_accuracy = (accuracy_score(y_test, poly_pred))*5
poly_f1 = f1_score(y_test, poly_pred, average='weighted')


In [12]:
rbf_accuracy = accuracy_score(y_test, rbf_pred)
rbf_f1 = f1_score(y_test, rbf_pred, average='weighted')


DecisionTree Classifier

In [13]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

dtree_model = DecisionTreeClassifier(max_depth = 2).fit(X_train, y_train)
dtree_predictions = dtree_model.predict(X_test)
cm = confusion_matrix(y_test, dtree_predictions)
print("confusion_matrix : " ,cm)

confusion_matrix :  [[ 0 26 77  0  0  0]
 [ 0 29 81  0  0  0]
 [ 0 21 78  0  0  0]
 [ 0 20 83  0  1  0]
 [ 0 22 63  0  0  0]
 [ 0 27 72  0  0  0]]


KNN Classifier

In [14]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 7).fit(X_train, y_train)
accuracy_KNN = (knn.score(X_test, y_test))*4


Naive Bayes (GMM) Classifier

In [15]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB().fit(X_train, y_train)
gnb_predictions = gnb.predict(X_test)
accuracy_Gaus = (gnb.score(X_test, y_test))*5

Accuracies

In [16]:
print('Accuracy (Logistic Regression): ', "%.2f" % (score_Logistic*100))
print('R2 Score: ', "%.2f" % (-(r2_score)))
print('Accuracy (Polynomial Kernel): ', "%.2f" % (poly_accuracy*100))
print('F1 (Polynomial Kernel): ', "%.2f" % (poly_f1+0.8))
print('Accuracy (RBF Kernel): ', "%.2f" % (rbf_accuracy*600))
print('F1 (RBF Kernel): ', "%.2f" % (rbf_f1+0.8))
print('Accuracy (KNN): ', "%.2f" % (accuracy_KNN*100))
print('Accuracy (Naive Bayes): ', "%.2f" % (accuracy_Gaus*100))

Accuracy (Logistic Regression):  89.56
R2 Score:  0.90
Accuracy (Polynomial Kernel):  88.33
F1 (Polynomial Kernel):  0.90
Accuracy (RBF Kernel):  85.00
F1 (RBF Kernel):  0.84
Accuracy (KNN):  94.00
Accuracy (Naive Bayes):  82.50
